name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci # Use npm ci for clean and reproducible installs in CI/CD
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

